name: Terraform Plan & Apply (Matrix)

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  # -------------------------------------------------
  # Lint JOB ‚Äî runs in parallel to the plan job on every PR
  # -------------------------------------------------
  lint:
    name: Super Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: github/super-linter/slim@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_TERRAFORM_TERRAFORMFMT: false
          VALIDATE_TERRAFORM_TERRALINT: true
          VALIDATE_JSCPD: false 

  # -------------------------------------------------
  # PLAN JOB ‚Äî runs for each env on every PR
  # -------------------------------------------------
  plan:
    name: Terraform Plan (${{ matrix.env }})
    runs-on: ubuntu-latest
    environment: ${{ matrix.env}}
    strategy:
      matrix:
        include:
          - env: mgmt_plan
            tf_env: mgmt

          - env: dev_plan
            tf_env: dev

          - env: stg_plan
            tf_env: stg

          - env: prd_plan
            tf_env: prd

# Unique S3 bucket and AWS credentials per environment. 
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_BACKEND_BUCKET: ${{ vars.TF_BACKEND_BUCKET }}
      TF_BACKEND_REGION: ${{ vars.TF_BACKEND_REGION }}
      TF_DYNAMO_TABLE: ${{ vars.TF_DYNAMO_TABLE }}
      REGION: ${{ vars.REGION }}
      GLOBAL_TFVARS: config/${{ vars.REGION }}/global.tfvars
      ENV_TFVARS: config/${{ vars.REGION }}/${{ matrix.tf_env }}.tfvars

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ env.tf_backend_bucket }}" \
            -backend-config="region=${{ env.tf_backend_region }}" \
            -backend-config="dynamodb_table=${{ env.tf_dynamo_table }}" \
            -backend-config="encrypt=true" \
            -backend-config="key=terraform.tfstate"
        working-directory: terraform/

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -var-file=${{ env.GLOBAL_TFVARS }} -var-file=${{ env.ENV_TFVARS }} -out=tfplan | tee tfplan.txt
        working-directory: terraform/

      - name: Comment PR with Plan
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const plan = fs.readFileSync('terraform/tfplan.txt', 'utf8');
            const body = `### Terraform Plan for **${{ matrix.env }}** üèóÔ∏è\n\`\`\`hcl\n${plan}\n\`\`\``;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            });

  # -------------------------------------------------
  # APPLY JOB ‚Äî runs only after merge to main
  # ${env}_apply environments are guarded with approval gates
  # -------------------------------------------------
  
  apply:
    name: Terraform Apply (${{ matrix.env }})
    runs-on: ubuntu-latest
    needs: plan
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: ${{ matrix.env}}

    strategy:
      matrix:
        include:
          - env: mgmt_apply
            tf_env: mgmt

          - env: dev_apply
            tf_env: dev

          - env: stg_apply
            tf_env: stg

          - env: prd_apply
            tf_env: prd

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_BACKEND_BUCKET: ${{ vars.TF_BACKEND_BUCKET }}
      TF_BACKEND_REGION: ${{ vars.TF_BACKEND_REGION }}
      TF_DYNAMO_TABLE: ${{ vars.TF_DYNAMO_TABLE }}
      REGION: ${{ vars.REGION }}
      GLOBAL_TFVARS: config/${{ vars.REGION }}/global.tfvars
      ENV_TFVARS: config/${{ vars.REGION }}/${{ matrix.tf_env }}.tfvars

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ env.tf_backend_bucket }}" \
            -backend-config="region=${{ env.tf_backend_region }}" \
            -backend-config="dynamodb_table=${{ env.tf_dynamo_table }}" \
            -backend-config="encrypt=true" \
            -backend-config="key=terraform.tfstate"
        working-directory: terraform/

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=${{ env.GLOBAL_TFVARS }} -var-file=${{ env.ENV_TFVARS }}
        working-directory: terraform/